# Generated by Django 4.2.3 on 2023-07-27 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'default_related_name': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('memo', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='calculator.report')),
            ],
            options={
                'default_related_name': 'transactions',
            },
        ),
    ]
